# Generated by Django 3.2 on 2021-05-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=50)),
                ('item_category', models.CharField(choices=[('tv', 'televeision'), ('rdo', 'radio'), ('tstr', 'toaster')], default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('item_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='code_snippets.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='code_snippets.item')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ManyToManyField(default='', related_name='order', to='code_snippets.Order')),
            ],
        ),
    ]
